language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
#  - SYMFONY_VERSION=dev-master - is failing due to dependency issues requiring symfony 2.4 security core

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - chrisjohnson00@hotmail.com
